In [2]:
import sqlite3
import pandas as pd

In [4]:
query = '''
SELECT *
FROM employees
WHERE vacation_hours > 40;
'''
with sqlite3.connect('employees.db') as conn:
    df = pd.read_sql_query(query, conn)

df.head()

,customer_id,email_address,vacation_hours,sallaried,title
0,2,keith0@adventure-works.com,80,1,manager
1,3,donna0@adventure-works.com,69,1,sales rep
2,4,janet1@adventure-works.com,49,1,sales rep
3,5,lucy0@adventure-works.com,49,1,sales rep
4,6,rosmarie0@adventure-works.com,88,1,manager

In [16]:
df['employee_name'] = df['email_address'].str.extract(r'([a-z]+)(?=\d)')
df.head()
df.to_excel('out/employees_with_high_vaca_hours.xlsx', index=False)

HR Question 2

In [17]:
query = '''
SELECT *
FROM employees
'''
with sqlite3.connect('employees.db') as conn:
    df = pd.read_sql_query(query, conn)

df.head()

,customer_id,email_address,vacation_hours,sallaried,title
0,1,orlando0@adventure-works.com,18,0,sales rep
1,2,keith0@adventure-works.com,80,1,manager
2,3,donna0@adventure-works.com,69,1,sales rep
3,4,janet1@adventure-works.com,49,1,sales rep
4,5,lucy0@adventure-works.com,49,1,sales rep

In [21]:
df_grouped = df.groupby(['sallaried', 'title']).mean('vacation_hours')
df_grouped.head()
df.to_excel('out/avg_PTO.xlsx', index=False)